# # These are supported funding model platforms

# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with a single Liberapay username
# issuehunt: # Replace with a single IssueHunt username
# otechie: # Replace with a single Otechie username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

# # Donations
# # I accept donations in cryptocurrencies, anything helps. Thank you.

# BTC: 3G3zsvcxgomdERYTSjeX4iBJYMfFfCgFmn

# ETH: 0x227cc9c06db03563300fa7c2d0b0a34b370f5987

# DOGE: DNNsSrk767w9K1eaqc2tQSvJ4mzfBpw4RP

# BNB: bnb1rlka4xf6h8p8nlpf8szczmcyugdktptstgham0

# XMR: 86vsoW6jsTzcvGZxKVG1PxfsSqUzrMuqvKxLGCXZ3RcNY7VyvhcgiimciW5ZsHyrKUGCpqFPjDG7iMu9sSoveZDxMeGpqCb

# ZCASH: t1fkojdhoTTQmrPSExCLMuV6D3a2jxESGtL

# ADA: DdzFFzCqrhtBuwQRtRKNSVca58HDwicLx5aDWn8K5pyg36665BL5s6WBLAc9bCTxWk15MFiefoerCRiuxysW7Sy4RQJ6UM2vWXoCg98z

github: ["ehgp"]
